[project]
name = "second-layer"
version = "0.1.0"
description = "Simple encrypt/decrypt text tool with key generator."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=45.0.3",
    "py2app>=0.28.8",
    "setuptools>=80.9.0",
    "jaraco.text>=4.0.0"
]
